const {
  NELSONRULE01,
  NELSONRULE01_DESC,
  NELSONRULE02,
  NELSONRULE02_DESC,
  NELSONRULE03,
  NELSONRULE03_DESC,
  NELSONRULE04,
  NELSONRULE04_DESC,
  NELSONRULE05,
  NELSONRULE05_DESC,
  NELSONRULE06,
  NELSONRULE06_DESC,
  NELSONRULE07,
  NELSONRULE07_DESC,
  NELSONRULE08,
  NELSONRULE08_DESC,
} = require('./rules');

const {
  NELSONRULES_ALL_TRIGGERS,
  NELSONRULES_ALL_VALUES,
} = require('./summaries');

module.exports = {
  NELSONRULE01,
  NELSONRULE01_DESC,
  NELSONRULE02,
  NELSONRULE02_DESC,
  NELSONRULE03,
  NELSONRULE03_DESC,
  NELSONRULE04,
  NELSONRULE04_DESC,
  NELSONRULE05,
  NELSONRULE05_DESC,
  NELSONRULE06,
  NELSONRULE06_DESC,
  NELSONRULE07,
  NELSONRULE07_DESC,
  NELSONRULE08,
  NELSONRULE08_DESC,
  NELSONRULES_ALL_TRIGGERS,
  NELSONRULES_ALL_VALUES,
};
